### PR TITLE
Improve README & improve CSS

### PR DESCRIPTION
**Pull request by cheeaun**
Changes:

- README got simplified and has more straight-forward instructions
- Code changes
    - SVG changed to the one with word 'Singapore'
    - Remove some `flex`es
    - Mobile optimized styles

### CODE REVIEW

**Comment by cheeaun** [comment]
@hongkheng ^

**Comment by cheeaun** [comment]
Desktop:
localhost-1313-

Mobile:

**Comment by cheeaun** [comment]
Latest changes now synced with `npm-fix` branch 👍

**Comment by cheeaun** [comment]
Running `yarn dev` or `npm run dev`:
screen shot 2017-08-07 at 8 46 22 pm

**Review by hongkheng — APPROVED** [review]

**Comment by hongkheng** [comment]
@cheeaun thanks and I shall approve

**Pull request merged**
