### PR TITLE
Schedule + Registration 2020

### PR DESCRIPTION
**Pull request by hongkheng**
# Description

- Add registration link to home
home2020

- Add new schedule 2020
schedule2020

### CODE REVIEW

**Review by elfgoh — CHANGES_REQUESTED** [review]
I am basing my review on the screenshot. 

- `Nicolas Frankel`. 2nd word not capitalized
- Securing Singapore with AR speaker is wrong

**Comment by hongkheng** [comment]
Fixed:

Screen Shot 2017-09-17 at 10 30 52 PM

Screen Shot 2017-09-10 at 9 11 05 PM

**Comment by hongkheng** [comment]
Fixed:

Screenshot 2020-09-11 at 10 57 41 AM
Screenshot 2020-09-11 at 10 57 35 AM

**Review by elfgoh — APPROVED** [review]
Seems like `Siddhant Shrivastava` is also a speaker for `Securing Singapore with Augmented Reality: a pandemic-proof prototype`. Please help to amend and then merge after that 🙇

**Pull request merged**
