### PR TITLE
Add FB links for talks

### PR DESCRIPTION
**Pull request by cheeaun**
Add 'Read more details 👉' to descriptions of each talks.

Looks like this:
screen shot 2017-11-10 at 10 46 01 pm

### CODE REVIEW

**Comment by elfgoh** [comment]
Or replace `Read more details` with `...` to represent an ellipsis? Pointing icon remains

**Review by elfgoh — APPROVED** [review]

**Comment by cheeaun** [comment]
I think 'More details' is short enough to be understandable, '...' is probably too vague 🤔

**Comment by elfgoh** [comment]
Agree with your assessment. Let's go with `More details` then?

**Comment by elfgoh** [comment]
LGTM

**Pull request merged**
