### PR TITLE
fix: landing page terminal and commands

### LINKED ISSUE #202: [CONF-2022] update registration command
image

Need to update that registration is now open

### PR DESCRIPTION
**Pull request by MisterDoobDoob**
Fixes #202

### CODE REVIEW

**Review by elfgoh — APPROVED** [review]
LGTM. Btw if it isn't too much to ask, possible to change the volunteer link to `Volunteer with us`. Can be same PR

**Comment by MisterDoobDoob** [comment]
> LGTM. Btw if it isn't too much to ask, possible to change the volunteer link to `Volunteer with us`. Can be same PR

Done, it was forcibly jumping users to a new tab which wasn't consistent with the behavior of other commands, so I commented out that function

**Comment by elfgoh** [comment]
>  "volunteer": "https://bit.ly/geekcampsg-volunteer-2022",

@MisterDoobDoob actually I meant that the JSON portion should be changed as what I mentioned. The command changes work though

**Review by elfgoh — APPROVED** [review]
LGTM

**Pull request merged**
