### PR TITLE
Link to site github repo on footer

### PR DESCRIPTION
**Pull request by cheeaun**
Perhaps need better copy than 'Fork this site'? Or not?

### CODE REVIEW

**Comment by hongkheng** [comment]
Or something like "Fork and contribute".

**Comment by elfgoh** [comment]
What about simply the Github fork banner like on [gophercon website](https://2017.gophercon.sg/)?

Or simply `Github`

**Comment by elfgoh** [comment]
I think those looking to send PRs and create forks can intuitively follow the github link

**Comment by cheeaun** [comment]
If it's "GitHub", should it link to this repo, or generic https://github.com/GeekcampSG ?

**Comment by elfgoh** [comment]
Let's link to the website? i think people can easily follow the trace... if they are upset enough they can send PRs :p

**Review by elfgoh — APPROVED** [review]

**Pull request merged**
