### PR TITLE
gatsby -> astro

### LINKED ISSUE #135: Abstract console content into JS data object
https://github.com/GeekcampSG/geekcampsg.github.io/blob/1596899108d475afc72abcdba857061dc6864131/src/sections/1.landing.js#L45-L175
can be easily abstracted for ease in editing. Something like:
```js
const config = {
    [{
       text: "title",
       color: "y"
     }]: "GeekcampSG 2020 Online",
    [{
       text: "dates",
       color: "y"
     }]: {
          [{
               text: "day1",
               color: "y"
          }]: {
               [{
                    text: "start",
                    color: "y"
               }]: "2020-09-19T14:00",
               [{
                    text: "end",
                    color: "y"
               }]: "2020-09-19T18:00"
          }
     },
     [{
          text: "location",
          color: "r",
     }]: '<a href="https://bit.ly/geekcampsg2020" rel="noopener noreferrer" target="_blank">bit.ly/geekcampsg2020</a>'
}
```
and then render accordingly with `dangerouslySetInnerHTML` whenver appropriate

### LINKED ISSUE #191: [CONF-2022] refresh section what people says

### LINKED ISSUE #201: speakers to 3x3 grid
since some of the speaker's photos are low-res, what if we reduced the height*width and make the 2x2 into a 3x3? just food for thought.

### LINKED ISSUE #206: Terminal command bonus is not working
Seems like an easter egg for the previous geekcamp.sg, but entering `bonus `doesn't work any more, directing to a #bonus that no longer exists. To remove/fix?

### PR DESCRIPTION
**Pull request by tanhauhau**
A thing frontend devs love to do: rewrite into a new framework.
This time round, I attempt to try the latest fad: [Astro](https://astro.build/).

Of course, at the same time, I took the liberty to cleanup the tickets:
- Closes #206
- Closes #201
- Closes #191
- Closes #135

Beyond the ticketed issues
- i've cleaned up the game code, which should be much more playable:
  - high score
  - alien spawning in increasing frequency
  - fullscreen mode
  - konami cheat codes 🙈

### CODE REVIEW

**Comment by cheeaun** [comment]
Very very cool. Did a quick comparison on the JS payload here:

Original (176KB) - excluding 3rd-party + CF scripts:
Screenshot 2022-10-13 at 6 07 56 PM

Astro (9.9KB) - excluding 3rd-party scripts **💥 17X smaller 💥**:
Screenshot 2022-10-13 at 6 08 25 PM

**👉 Here is a WebPageTest Comparison page: https://www.webpagetest.org/video/compare.php?tests=221013_BiDcTP_8AD,221013_BiDcR1_8AE 👈**

Few notes:

- Astro one has higher payload because the twitter tweet embed injects lots of JS and a huge image 😆 
- Current geekcamp site somehow has Cloudflare scrape shield turned on, so it injects a `email-decode.min.js`. Also has Rocket Loader turned on which seems to intercept how the JS is loaded (CF tries to be smart about this). Perhaps someone should turn it off?
- From WPT comparison page, Astro one loads visually faster, but the CLS, load time and number of requests are *heavily affected* by the Twitter embed 😆

**Comment by tanhauhau** [comment]
yea... i was a bit sad that the twitter embeds overwhelmingly offset all the bundle size reduction

**Comment by cheeaun** [comment]
@tanhauhau there are some static renderers out there:

- https://github.com/transitive-bullshit/react-static-tweets
- https://static-tweet.vercel.app/

or… screenshot: https://themaninblue.com/experiment/screenshot-a-tweet/

or… DIY style it 😜

**Comment by hongkheng** [comment]
Nice! Wan to shift from react to svelte. Consider after the conference.

**Comment by hongkheng** [comment]
@tanhauhau how much more work is there needs to be done? Think there are ppl wanting to raise pull requests to add new changes.

**Comment by tanhauhau** [comment]
@hongkheng actually everything is done. u can look at the preview

@cheeaun ooh thanks for your examples, i manage to steal some inspiration over:
- calling tweeter api during build and pre-render the tweet html.

**Review by hongkheng — APPROVED** [review]

**Comment by hongkheng** [comment]
LGTM going to merge

**Comment by cheeaun** [comment]
Hmm… FYI, Cloudflare rocket loader (and email decoder) JS is still there. Not a big problem but kinda redundant 😅 🙏

**Comment by tanhauhau** [comment]
where is this coming from? is it the netlify settings? @hongkheng do you know how do we get into netlify admin?

**Comment by hongkheng** [comment]
Have to ask @elfgoh for access. My access was removed recently.

**Comment by elfgoh** [comment]
> Hmm… FYI, Cloudflare rocket loader (and email decoder) JS is still there. Not a big problem but kinda redundant 😅 🙏

@cheeaun thanks for highlighting this. Can I understand why it is redundant? 🙇

I am unfamiliar with both and my only contexts are:
- https://blog.cloudflare.com/we-have-lift-off-rocket-loader-ga-is-mobile/
- https://bobcares.com/blog/cloudflare-email-protection-decoder/

**Comment by cheeaun** [comment]
@elfgoh

Technically CF Rocket Loader's intention is good. A lot of sites are slow due to too many (blocking) JS 😆  For this case, it's a simple page, not a lot of JS, and nowadays bundlers like Vite/Astro do their own things to handle web perf.

As for the email decoder… the JS find emails on the page and obfuscate them (with a non-email link), that's it 😅

**Comment by elfgoh** [comment]
> Technically CF Rocket Loader's intention is good. A lot of sites are slow due to too many (blocking) JS 😆 For this case, it's a simple page, not a lot of JS, and nowadays bundlers like Vite/Astro do their own things to handle web perf.

Ok. So for CF Rocket Loader, no detrimental effect even if left on, although it has no benefit for us given the features of Astro?

If yes, then maybe leave it on, since there is no telling what framework/bundler will be used in the future... and handing and taking over of account credentials may lapse

In short, leave it as status quo as it is a "smart" default?

> 
> As for the email decoder… the JS find emails on the page and obfuscate them (with a non-email link), that's it 😅


I guess can also leave as it is a "smart" default? Fwiw, these may have been on by default instead of being explicitly set

**Comment by cheeaun** [comment]
@elfgoh sure can, yeah not detrimental 🙇 👍

**Pull request merged**
