### PR TITLE
feat: add food and silver sponsor

### LINKED ISSUE #216: [CONF-2022] Add Prolive as silver sponsor
Waiting for logo

### LINKED ISSUE #217: [CONF-2022] add imToken as Food sponsor
Normal
Stack_Normal

### PR DESCRIPTION
**Pull request by tanhauhau**
Closes #217 
Closes #216

### CODE REVIEW

**Review by hongkheng — APPROVED** [review]

**Comment by elfgoh** [comment]
Can we make the section `Sponsor` plural since there are multiple sponsors now?

**Comment by elfgoh** [comment]
There will be a gold sponsor as well. I will file an issue in a bit. Is it possible to make the silver and gold sponsor logos relatively smaller to the platinum sponsors ie food and venue?

**Comment by tanhauhau** [comment]
ok i wait for the gold sponsors and then make all the change together

**Comment by elfgoh** [comment]
> ok i wait for the gold sponsors and then make all the change together

@tanhauhau gold sponsor is in #219. That is the last sponsor

**Comment by tanhauhau** [comment]
ok @elfgoh 
- added gold sponsor
- updated the "sponsors" heading
- updated the sponsor logo size

**Pull request merged**
